@MonthlyBudget.Api_HostAddress = http://localhost:5226

POST {{MonthlyBudget.Api_HostAddress}}/budget
Content-Type: application/json

{
  "month": "2026-03",
  "income": 6500
}

###

POST {{MonthlyBudget.Api_HostAddress}}/budget/1/expense
Content-Type: application/json

{
  "name": "Paliwo",
  "amount": 320.50,
  "category": "Transport"
}

###

GET {{MonthlyBudget.Api_HostAddress}}/budget/1
Accept: application/json

###
